# Generated by Django 2.1.7 on 2019-03-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationexternalities',
            name='classification',
            field=models.CharField(choices=[('red', 'Red'), ('seguridad', 'Seguridad')], default='Seleccione la clasificación de la incidencia', max_length=250, verbose_name='clasificación'),
        ),
    ]
