# Generated by Django 2.1.7 on 2019-03-23 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificationApp', '0002_registrationexternalities_classification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationexternalities',
            options={'verbose_name': 'incidencia', 'verbose_name_plural': 'incidencias'},
        ),
    ]
