# Generated by Django 2.1.7 on 2019-03-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationApp', '0003_auto_20190322_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationexternalities',
            name='classification',
            field=models.CharField(choices=[('red', 'Red'), ('seguridad', 'Seguridad')], default='Red', max_length=250, verbose_name='clasificación'),
        ),
    ]
