# Generated by Django 2.1.7 on 2019-03-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationApp', '0004_auto_20190322_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationexternalities',
            name='revised',
            field=models.BooleanField(default=False, verbose_name='revisada'),
        ),
    ]
