# Generated by Django 2.1.7 on 2019-03-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationApp', '0007_auto_20190322_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationexternalities',
            name='userIncidents',
            field=models.CharField(default=False, max_length=250, verbose_name='Usuario'),
        ),
    ]
