# Generated by Django 2.1.7 on 2019-03-23 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notificationApp', '0008_registrationexternalities_userincidents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationexternalities',
            name='userIncidents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
