# Generated by Django 2.1.7 on 2019-03-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationApp', '0009_auto_20190322_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationexternalities',
            name='revised',
            field=models.BooleanField(verbose_name='revisada'),
        ),
    ]
