# Generated by Django 2.1.7 on 2019-03-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationApp', '0010_auto_20190322_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationexternalities',
            name='revised',
            field=models.BooleanField(default=False, verbose_name='revisada'),
        ),
    ]
