# Generated by Django 2.1.7 on 2019-03-23 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificationApp', '0012_auto_20190322_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationexternalities',
            old_name='userToIncidents',
            new_name='userIncidents',
        ),
    ]
