# Generated by Django 2.1.7 on 2019-03-23 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificationApp', '0013_auto_20190322_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationexternalities',
            name='userIncidents',
        ),
    ]
