# Generated by Django 2.1.7 on 2019-03-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationApp', '0014_remove_registrationexternalities_userincidents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationexternalities',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
